---
extends:
  - react-app
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', 'cypress']
env:
  cypress/globals: true
rules:
  prefer-template: error
  prefer-const: error
  '@typescript-eslint/explicit-member-accessibility': 'off'
  '@typescript-eslint/explicit-function-return-type': [error, {allowExpressions: true}]
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-empty-interface': 'warn'
  '@typescript-eslint/no-use-before-define': [error, nofunc]